/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRepairRouteImport } from './routes/_authenticated.repair'
import { Route as AuthenticatedInspectionRouteImport } from './routes/_authenticated.inspection'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated.health'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated.emergency'
import { Route as AuthenticatedDronesRouteImport } from './routes/_authenticated.drones'
import { Route as AuthenticatedDigitalTwinRouteImport } from './routes/_authenticated.digital-twin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRepairRoute = AuthenticatedRepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInspectionRoute = AuthenticatedInspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDronesRoute = AuthenticatedDronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDigitalTwinRoute =
  AuthenticatedDigitalTwinRouteImport.update({
    id: '/digital-twin',
    path: '/digital-twin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/drones': typeof AuthenticatedDronesRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/health': typeof AuthenticatedHealthRoute
  '/inspection': typeof AuthenticatedInspectionRoute
  '/repair': typeof AuthenticatedRepairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/drones': typeof AuthenticatedDronesRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/health': typeof AuthenticatedHealthRoute
  '/inspection': typeof AuthenticatedInspectionRoute
  '/repair': typeof AuthenticatedRepairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/digital-twin': typeof AuthenticatedDigitalTwinRoute
  '/_authenticated/drones': typeof AuthenticatedDronesRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/inspection': typeof AuthenticatedInspectionRoute
  '/_authenticated/repair': typeof AuthenticatedRepairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/digital-twin'
    | '/drones'
    | '/emergency'
    | '/health'
    | '/inspection'
    | '/repair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/digital-twin'
    | '/drones'
    | '/emergency'
    | '/health'
    | '/inspection'
    | '/repair'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/digital-twin'
    | '/_authenticated/drones'
    | '/_authenticated/emergency'
    | '/_authenticated/health'
    | '/_authenticated/inspection'
    | '/_authenticated/repair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/repair': {
      id: '/_authenticated/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof AuthenticatedRepairRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspection': {
      id: '/_authenticated/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof AuthenticatedInspectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drones': {
      id: '/_authenticated/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof AuthenticatedDronesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/digital-twin': {
      id: '/_authenticated/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof AuthenticatedDigitalTwinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDigitalTwinRoute: typeof AuthenticatedDigitalTwinRoute
  AuthenticatedDronesRoute: typeof AuthenticatedDronesRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedInspectionRoute: typeof AuthenticatedInspectionRoute
  AuthenticatedRepairRoute: typeof AuthenticatedRepairRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDigitalTwinRoute: AuthenticatedDigitalTwinRoute,
  AuthenticatedDronesRoute: AuthenticatedDronesRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedInspectionRoute: AuthenticatedInspectionRoute,
  AuthenticatedRepairRoute: AuthenticatedRepairRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
